project:
  type: website

execute:
  freeze: auto

website:
  title: "MESA Lab"
  navbar:
    right:
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: cosmo
    css: styles.css
